### ISSUE TITLE
Feature request: specify an additional class for the concepts

### ISSUE THREAD

**Issue by jennet** [Swirrl/table2qb#134]
I would like to specify a additional uri for a class for the resulting concepts in a code list pipeline, e.g. 

`exec codelist-pipeline --codelist-csv .... --concept-type-uri http://example.org/def/FloodRiskSource`

to produce output such as 

```
<http://example.org/fpe/concept/risk-source/rivers>
  a skos:Concept, http://example.org/def/FloodRiskSource;
```

What do you think @Robsteranium @lkitching ?

**Comment by Robsteranium** [comment]
I like the idea of adding classes to codes.

Indeed you can see the vestiges of this the remain from historical transformations: the components-pipeline creates an `rdfs:range` property. We probably ought to make that configurable too (instead of defaulting to `classize`-ing the label).

What about situations where different codes would need different classes - e.g. a table of geographies would need different `pmdkos:ConceptLevel`s?

We _could_ achieve that with a cli argument by running the codes for each class separately. I'm a little wary of that though as it shifts a data concern into an execution concern - perhaps it should be a column not a cli arg?

Thus an alternative proposal would be to add an optional "Type" column to the codelist-pipeline and "Range" to the components-pipeline.

Wdyt?
