### ISSUE TITLE
issue in example employment

### ISSUE THREAD

**Issue by PaulZH** [Swirrl/table2qb#60]
in cube.ttl <http://statistics.gov.scot/def/measure-properties/count>
while in components.ttl <http://statistics.gov.scot/def/measure/count>

As it is now example fails on IC-3. 
DSD includes measure
Every qb:DataStructureDefinition must include at least one declared measure. 
ASK {   ?dsd a qb:DataStructureDefinition .   FILTER NOT EXISTS { ?dsd qb:component [qb:componentProperty [a qb:MeasureProperty]] } }

**Comment by BillSwirrl** [comment]
I have pushed corrections to columns.csv that fixes the above problems, so that the generated cube file is consistent with the gender.ttl codelist and the components.ttl

Note that IC-3 as written in the spec still fails, because in the DSD the component is linked to the component property by the qb:measure  predicate rather than by qb:componentProperty.

Because qb:measure is a subproperty of qb:componentProperty, I thought this was valid/correct,  but it doesn't pass that test.

This modified version of the IC-3 does pass after the changes I made

```
PREFIX qb: <http://purl.org/linked-data/cube#>
ASK { ?dsd a qb:DataStructureDefinition . FILTER NOT EXISTS { ?dsd qb:component [qb:measure [a qb:MeasureProperty]] } }
```

What's your view on this @PaulZH - do you think it is incorrect to use qb:measure here instead of qb:componentProperty ?

**Comment by PaulZH** [comment]
No, it is correct since it is a subproperty and with rdfs reasoning on the test passes.
