### ISSUE TITLE
DOS line endings in codelist CSV misses labels

### ISSUE THREAD

**Issue by ajtucker** [Swirrl/table2qb#68]
We came across an odd issue running the `table2qb` `codelist-pipeline` where the results are different when the input CSV file has DOS style line-endings.

These two files differ by line endings:

DOS: https://raw.githubusercontent.com/ONS-OpenData/ref_migration/41e267a3ee2fb5660429facfdf5c24385f82951e/codelists/residence.csv

Unix: https://raw.githubusercontent.com/ONS-OpenData/ref_migration/e107e466f09bd135bedb0e0f13ab0e3596b60f1e/codelists/residence.csv

Running them through `table2qb`, the former misses the `rdfs:label` and `skos:prefLabel` statements that are included in the latter.

**Comment by Robsteranium** [comment]
This is probably because the BOM gets interpreted as part of the column header (thus it no longer get's matched as `"Label"`). We can [change the reader](https://github.com/clojure/data.csv#byte-order-mark) to strip this.

Since clojure/data.csv doesn't support doing anything with the mark, we'd effectively be silently ignoring it although I suspect this is probably fine for now.

**Comment by Robsteranium** [comment]
Should be resolved by 01f24612. Please re-open if this is still a problem.
