### ISSUE TITLE
--column-config is misleadingly named

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/table2qb#74]
`--column-config` is misleadingly named, as not everything in the file is a column; it also specifies measure's too (which occur in row data) for the measure type dimension.

I think we should consider deprecating this flag (still support it for legacy users) and either:

1. Add a new flag named `--component-config`.
2. Keep the name `--column-config` and require a new extra option `--measures-config` for a file containing the measures.

I think `1` is my preferred option, though I also wonder why measures aren't specified with components.

**Comment by Robsteranium** [comment]
Which rows in the column-config file are not columns?

The name comes from the idea of a `csvw:column`, these are not necessarily components - e.g. the value column. The measures appear in rows because they are dimension-values for the measure-type dimension. They are also columns but we don't require this explicitly because we can infer it from measure-type, allowing users to specify a single value column. We could do away with the value column and instead have a column for each measure (similar to the plans for supporting multi-measure observations #23).

Introducing an unrelated `--component-config` option might become confusing for those using the `components-pipeline`.

**Comment by RickMoynihan** [comment]
> Which rows in the column-config file are not columns?

It may be the example I've seen over someones shoulder (i.e. not in a repo yet) wasn't quite right; but e.g. here

[Count](https://github.com/Swirrl/table2qb/blob/master/examples/employment/csv/components.csv#L3) is not a column in the [input.csv](https://github.com/Swirrl/table2qb/blob/master/examples/employment/csv/input.csv).  

> The name comes from the idea of a csvw:column

Ahh ok, that makes sense.  I assumed it was because because most of the rows in that file but not all map one-to-one with columns in the input, but the measures behave differently.  It seems strange that the measureType dimension is special cased from other dimensions.

It's not a big deal because what we have works great, and I understand we inherit this complexity from the `qb` spec; but I think it is a point of confusion.  

I could also be misunderstanding things here as my exposure to table2qb at the moment has just been via other people, rather than using it directly myself.  

If you have any thoughts on whether there is a UX level problem here or not though; and whether it can be resolved or if it's inherent with the domain that would be useful.  Will also ponder this a bit more 🤔

**Comment by Robsteranium** [comment]
We've since taken some steps to clarify how table2qb inputs are declared.

First, there's some [improved documentation](https://github.com/Swirrl/table2qb/blob/master/doc/usage.md) which should help to make everything a bit clearer.

More substantively, we've added support for using measures in columns. This only works for for multi-measure observations at the moment. The specification in issue #101 would extend this to measures-dimension observations, allowing users to use measure components as columns instead of the magic `Value` column. As per that thread, this would remove a source of confusion at the expense of verbosity so we might continue to support both the clearer measures-columns declaration _and_ the succincter values-column declaration going forward.

I'm therefore going to close this issue now. Thanks for the report. If it's still confusing, then perhaps we should add some more details to the docs or examples.
