### ISSUE TITLE
deps.edn workflow & support

### ISSUE THREAD

**Issue by RickMoynihan** [Swirrl/table2qb#75]
Add notes to docs about how to consume from the new `clj` tool and `deps.edn`, e.g.

```edn
:aliases {  :table2qb {:extra-deps {
                        {:git/url "https://github.com/Swirrl/table2qb/"
                         :sha "some-sha-here"}}
           :main-opts ["-m" "table2qb.main"
                               "exec" "cube-pipeline"
                               "--column-config" "foo/bar/components.csv"
                              ,,,,]}}
```

Then we can run at the commandline like so:

`$ clojure -A:table2qb blah blah`

Which will be handy in some projects, as it will mean some of our projects can just include a snippet in their `deps.edn` file and expose the tool to project users, without them having to fetch and install the jar etc.

Could also look at making this a `deps.edn` project (for `:git/url` support).

**Comment by Robsteranium** [comment]
This is a great suggestion and a nifty little way of using the library.

The [description provided by the above patch](https://github.com/Swirrl/table2qb#clojure-cli) looks good for the most part but it seems like you can't include a `:tag` without a `:sha` - indeed the `:tag` is optional and seems only to be descriptive - which strikes me as a bit of a poor design as you can specify a sha that has nothing to do with the tag! Perhaps it's supposed to be a generic tag, not a git tag. In any case I suggest we identify a sha in the snippet (so that it works) and potentially add a comment with the tag/ release number etc.
